### ISSUE TITLE
Documentation Fundamentally Confusing

### ISSUE THREAD

**Issue by dsanders11** [awsdocs/amazon-workmail-administration-guide#1] opened 2018-04-23 05:45 UTC
This is a bit of a rant, but it is not meant to be mean-spirited. It just comes from a place of deep frustration of how confusing WorkMail's documentation (but also WorkMail itself) is.

I tried WorkMail a year or so ago but abandoned pursing it because the documentation was confusing, and the pricing model didn't make sense for my use case: ~4 users who needed full access (including emails before their user was created) to a dozen email addresses (support@..., sales@...., blog@...). At the time I realized that for this to be possible each email would need to be a 'user' and this was not only confusing, but meant the pricing was out of whack, paying separately for a lightly used email address made little sense.

Fast forward to this last week, and there's a blog announcement about WorkMail that made me think this all had been improved and it would work for our use case:

> You can now share mailboxes among your team members. All users that have been granted access to a shared mailbox can send and receive emails using this mailbox without the need to manually share access credentials. 

Sounds great! That's exactly what I want. We'll make a mailbox for each email address (support@...) and share it among the ~4 team members and all will be great. So I spun up a WorkMail organization to try a test set up, and that's when things fall off the rails quickly.

From the blog post:

> To create a shared mailbox, create a mailbox in the Amazon WorkMail management console and select the Permissions tab. Then, add users and groups, and select whether they have Full Access, Send As, or Send on Behalf permissions for the mailbox.

First road block. I don't see anything about creating a new 'mailbox' in the management console. Searching the documentation for mailbox only talks about mailbox permissions. So I'm not scratching my head, the blog post clearly refers to mailbox but the documentation uses the term in passing, there's zero high-level mention of mailboxes. **What the heck is a mailbox?**

Look at the documentation more, look at groups. Find this description in the overview:

> Groups can be used as distribution lists in Amazon WorkMail for receiving emails for generic email addresses like sales@example.com or support@example.com.

Ok, great, that sounds like what I want. I'll create a group real quick to test, and add my user to it. I do so, but when I add my user, under permissions there's no option for 'Full Access' like was mentioned in the original blog post. Hmm, strange. So I try to access the group's email inbox from the WorkMail web client interface. It's not showing up there.

So I poke around more. Are users a 'mailbox'? The documentation doesn't say this, and the blog post clearly refers to mailboxes. So I try to create a new user. Username and full name? That's a bit confusing when I just want a 'mailbox', but I guess I can provide one. Wait, I can't use `support` as the username because I used it for the group which didn't do what I wanted? Ok, I'll go delete the group. Wait, I can't delete a group. I can only disable it. So now both the name and the email have been forever stolen by that group and I'm out of luck? Will I have to burn down my entire WorkMail and start over because I made a poor choice due to confusing documentation? Oh, looks like I can change the group email if I disable it, then re-enable it (changing it then), then disable it again.

Still can't change the name of the group, so my simple mistake has permanent ramifications, that's nice. So I name the user something else. Then I go to permissions, and there's the 'Full Access' that was missing earlier. So users are mailboxes? Wait, I can add a user as having mailbox permissions to their own 'mailbox'? What happens if I add the user under mailbox permissions, but don't chose 'Full Access'? Did I just remove the user's ability to access their own 'mailbox'? That's bizarre.

So, the documentation won't tell you it, but **users** are mailboxes, and so the $4/month per **user** actually refers to **mailboxes**.

This entire process was incredibly frustrating and has me writing off WorkMail permanently. It doesn't seem to have a coherent understanding of its own concepts and terminology, and the documentation provides no help instead providing conflicting advice (directly you to groups for a shared email when really you want a dedicated user), and the UI seems to let you make permanent decisions with no warning or recourse in addition to bizarre nonsense like removing a user's permission to their own 'mailbox' (AKA, user).

It's a shame because WorkMail fills a need and could be a great product, and I *want* to be a paying customer, but I can't figure out how to use it in a sane way and the documentation is a huge part of that.

**Comment by lkdavies** [comment] 2018-05-17 23:19
Hi @dsanders11 ,

Thanks for the feedback. I'm sorry to hear about the confusion caused by the differences between the blog post and the technical documentation. As the writer who inherited the current technical documentation, I'll attempt to address your comments.

The blog post you're referring to was meant to announce the launch of the [mailbox permissions](https://docs.aws.amazon.com/workmail/latest/adminguide/mail_perms_overview.html) feature, which allows WorkMail admins to set permissions for other users and/or groups to access a particular user's mailbox. 


RE: your question, 

> What the heck is a mailbox?

the technical documentation currently explains the concept of mailboxes in relation to users on the [Create New Users](https://docs.aws.amazon.com/workmail/latest/adminguide/add_new_user.html) Help page: 

> When you create new users, Amazon WorkMail creates mailboxes for them.

(I can see why the blog post was confusing here, but since the blog is separate from the technical documentation, I'll move on.)

RE: the concept of WorkMail groups used as distribution lists on the [Working with Groups](https://docs.aws.amazon.com/workmail/latest/adminguide/groups_overview.html) Help page: 

> Groups can be used as distribution lists in Amazon WorkMail for receiving emails for generic email addresses like sales@example.com or support@example.com.

The understanding is that a group used as a distribution list will receive email sent to a generic email address, and then distribute that email to the mailboxes of the users in that group. (Similar to how an Outlook email distribution list works.)

There's also a section on the [mailbox permissions](https://docs.aws.amazon.com/workmail/latest/adminguide/mail_perms_overview.html#manage_group_perms) Help page that explains why Groups cannot have Full Access permissions assigned: 

> Full Access permissions are not available for groups, because groups do not have a mailbox to access.


That being said, I'm not tech support, but based on the documentation here's what I would do as an admin in your particular situation. If I wanted individual mailboxes for each of the generic email addresses, I would create a new user for each generic email address. (I would also have the option to create new user accounts for each of my human users, but since that would cost more, I might consider having my human users each "own" one of the mailboxes for the generic email addresses.) 

Then, as the admin, I would [Enable Mailbox Permissions](https://docs.aws.amazon.com/workmail/latest/adminguide/mail_perms_overview.html#enable_mail_perms) for each other user that needed full access to the generic email mailboxes. 

If I didn't need individual mailboxes for each generic email address (but I just needed my human users to be able to receive and respond to those emails from their own mailboxes), I'd create new users for each of my human users only. Then I'd create groups for each of the generic email addresses and add my users to those groups. That would allow each user to receive email in their mailboxes from the group aliases. 

RE: the UI issues you mentioned, I'd recommend leaving feedback in the [Amazon WorkMail Forum](https://forums.aws.amazon.com/forum.jspa?forumID=191). It's also a good place to ask for help in situations such as the one you experienced.

In the meantime, can you help me understand what in particular could be changed in the technical documentation that would have helped in your situation? If there's something we're missing that could help other users, I want to make sure we cover it. 

Thanks!

**Comment by lkdavies** [comment] 2018-05-29 19:29
The WorkMail product team has suggested updates to the WorkMail concepts glossary definitions of User and Group, which are live here: 
https://docs.aws.amazon.com/workmail/latest/adminguide/what_is.html#workmail_concepts 

I'll close this issue, but if there are any other particular changes in the technical documentation that might help, please feel free to create a pull request for our review. Thanks!

**Closed as completed by lkdavies** 2018-05-29 19:29 UTC
